name: Deploy verifier backend to AWS Environment new account

on:
  workflow_run:
    workflows: ["Checks"]
    branches:  ["develop", "main"]
    types:
      - completed

jobs:
  build-backend:
    environment:
      name: ${{ github.event.workflow_run.head_branch }}

    name: Build and push latest image to AWS
    permissions:
      id-token: write
      contents: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Print Environment
        run: echo ${{ github.event.workflow_run.head_branch }}
